import {
  NAV_ITEM_TYPE_TITLE,
  NAV_ITEM_TYPE_COLLAPSE,
  NAV_ITEM_TYPE_ITEM,
} from "constants/navigation.constant";
import {SUPERADMIN, ADMIN, RESTAURANT, USER, SALES} from 'constants/roles.constant'

const navigationConfig = [
  {
    key: "restaurant",
    path: "",
    title: "Restaurant",
    translateKey: "nav.restaurant",
    icon: "restaurant",
    type: NAV_ITEM_TYPE_TITLE,
    authority: [ADMIN,SUPERADMIN,RESTAURANT],
    subMenu: [
      {
        key: "home",
        path: "/home",
        title: "Home",
        translateKey: "nav.home",
        icon: "home",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [RESTAURANT],
        subMenu: [],
      },
      {
        key: "dispatcher",
        path: "/restaurant/dispatcher/pending",
        title: "Dispatcher",
        translateKey: "nav.dispatcher",
        icon: "dispatcher",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [RESTAURANT],
        subMenu: [],
      },
      {
        key: "table",
        path: "/restaurant/table/show",
        title: "Table",
        translateKey: "nav.table",
        icon: "table",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [RESTAURANT],
        subMenu: [],
      },
      {
        key: "reservation",
        path: "/restaurant/reservation",
        title: "Reservation",
        translateKey: "nav.reservation",
        icon: "reservation",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [RESTAURANT],
        subMenu: [],
      },
      {
        key: "addons",
        path: "/restaurant/addons/show",
        title: "Addons",
        translateKey: "nav.addons",
        icon: "addons",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [RESTAURANT],
        subMenu: [],
      },
      {
        key: "products",
        path: "/restaurant/products/show",
        title: "Products",
        translateKey: "nav.products",
        icon: "product",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [RESTAURANT],
        subMenu: [],
      },
      {
        key: "combos",
        path: "/restaurant/combo/show",
        title: "Combo Menu",
        translateKey: "nav.combo",
        icon: "combo",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [RESTAURANT],
        subMenu: [],
      },
      {
        key: "category",
        path: "/restaurant/category/show",
        title: "Category",
        translateKey: "nav.category",
        icon: "category",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [RESTAURANT],
        subMenu: [],
      },
      {
        key: "cuisines",
        path: "/admin/cuisines/show",
        title: "Cuisines",
        translateKey: "nav.cuisines",
        icon: "category",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN,SUPERADMIN],
        subMenu: [],
      },
    ],
  },
  {
    key: "settings",
    path: "",
    title: "Setiings",
    translateKey: "nav.settings",
    icon: "cog",
    type: NAV_ITEM_TYPE_TITLE,
    authority: [],
    subMenu: [
      {
        key: "settings.account",
        path: "/settings/account/profile",
        title: "Account",
        translateKey: "nav.account",
        icon: "account_setting",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
    ],
  },
  {
    key: "leads",
    path: "",
    title: "Leads",
    translateKey: "nav.leads",
    icon: "leads",
    type: NAV_ITEM_TYPE_TITLE,
    authority: [SUPERADMIN, ADMIN],
    subMenu: [
      {
        key: "leads.create",
        path: "/leads/create_lead",
        title: "Create Lead",
        translateKey: "nav.create_lead",
        icon: "add_user",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [SUPERADMIN, ADMIN],
        subMenu: [],
      },
      {
        key: "leads.manage",
        path: "/leads/manage_lead",
        title: "Manage Leads",
        translateKey: "nav.manage_lead",
        icon: "users",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [SUPERADMIN, ADMIN],
        subMenu: [],
      },
    ],
  },
  {
    key: "verifications",
    path: "",
    title: "Verifications",
    translateKey: "nav.verification",
    icon: "",
    type: NAV_ITEM_TYPE_TITLE,
    authority: [SUPERADMIN, ADMIN],
    subMenu: [
      {
        key: "verifications.list",
        path: "/verification/user",
        title: "User Requests",
        translateKey: "nav.user_requests",
        icon: "verify",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [SUPERADMIN, ADMIN],
        subMenu: [],
      },
    ],
  },
];

export default navigationConfig;
